application: bites-without-borders
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins: 
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /images
  static_dir: static_files/images
- url: /css
  static_dir: static_files/css
- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest